import jsPDF from 'jspdf';
import { getFormById, FIELD_LABELS } from './formsRegistry';
import { getFieldPlaceholder } from './utils/getMissingDocuments';

interface GeneratePDFOptions {
  formId: string;
  data: Record<string, any>;
  profileData: Record<string, any>;
}

// Cyrillic font support would require embedding fonts
// For now, we'll generate a simple PDF with form data

export async function generatePDF({ formId, data, profileData }: GeneratePDFOptions): Promise<Blob> {
  const form = getFormById(formId);
  if (!form) {
    throw new Error(`Form not found: ${formId}`);
  }

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Note: For proper Cyrillic support, you would need to embed a font
  // This is a simplified version

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Header
  doc.setFontSize(12);
  doc.text('MIGRANTHUB', pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Title
  doc.setFontSize(14);
  // For Cyrillic, we'd need to use a proper font
  // Using transliteration or Unicode escape for demo
  doc.text(form.titleShort, pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Date
  doc.setFontSize(10);
  const today = new Date().toLocaleDateString('ru-RU');
  doc.text(`Data: ${today}`, margin, y);
  y += 10;

  // Separator
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Form data
  doc.setFontSize(10);

  const allData = { ...profileData, ...data };

  form.requiredFields.forEach((field) => {
    const label = FIELD_LABELS[field] || field;
    const rawValue = allData[field];
    const hasValue = rawValue !== undefined && rawValue !== null && rawValue !== '';

    let value: string;
    let isPlaceholder = false;

    if (hasValue) {
      value = String(rawValue);
    } else {
      // Use placeholder indicating which document is needed
      value = getFieldPlaceholder(field);
      isPlaceholder = true;
    }

    // Set gray color for placeholders
    if (isPlaceholder) {
      doc.setTextColor(128, 128, 128);
    } else {
      doc.setTextColor(0, 0, 0);
    }

    // For simplicity, we're using basic text
    // In production, use proper Cyrillic font
    doc.text(`${label}: ${value}`, margin, y);
    y += 8;

    // Check if we need a new page
    if (y > 270) {
      doc.addPage();
      y = margin;
    }
  });

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Additional fields from form data
  Object.entries(data).forEach(([key, value]) => {
    if (!form.requiredFields.includes(key) && value) {
      const label = FIELD_LABELS[key] || key;
      doc.text(`${label}: ${value}`, margin, y);
      y += 8;

      if (y > 270) {
        doc.addPage();
        y = margin;
      }
    }
  });

  // Signature line
  y += 20;
  doc.text('Podpis: _______________', margin, y);
  y += 10;
  doc.text('Data: _______________', margin, y);

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(
    'Generated by MigrantHub - migranthub.ru',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  return doc.output('blob');
}

export async function downloadPDF(options: GeneratePDFOptions): Promise<void> {
  const blob = await generatePDF(options);
  const form = getFormById(options.formId);

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${form?.id || 'document'}_${Date.now()}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function previewPDF(options: GeneratePDFOptions): Promise<void> {
  const blob = await generatePDF(options);
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
}

export async function sharePDF(options: GeneratePDFOptions): Promise<void> {
  const blob = await generatePDF(options);
  const form = getFormById(options.formId);
  const file = new File([blob], `${form?.id || 'document'}.pdf`, { type: 'application/pdf' });

  if (navigator.share && navigator.canShare({ files: [file] })) {
    await navigator.share({
      files: [file],
      title: form?.title || 'Document',
    });
  } else {
    // Fallback to download
    await downloadPDF(options);
  }
}
